language: node_js

node_js:
  - 9.8.0

env:
  global:
  - COVERALLS_REPO_TOKEN="lzZL8abK8jOtViY9FrqEomzb3rDypDT7w"

install:
  - npm install

notifications:
    email: false

# command to run tests
script:
  - npm test

after_success: npm coveralls
