language: node_js
node:
  - 9.8.0

# command to install dependencies
install:
  - npm install

notifications:
    email: false

cache:
  directories:
    - node_modules

# command to run tests
script:
  - npm run build
  - npm test

after_success: npm coveralls
